### ISSUE TITLE
How to configure and install?

### ISSUE THREAD

**Issue by Dazmed707** [SpaceR3/TewQ#3]
Guide for compiling and install rat?

**Comment by SpaceR3** [comment]
download the source, and install visual studio. Open the SLN file for client and Server. CLick compile

**Comment by Dazmed707** [comment]
where I configure the port and host where the connection should arrive

**Comment by SpaceR3** [comment]
??

**Comment by Dazmed707** [comment]
how to configure host (ip, dns) and port for receive conecctions?

**Comment by swagkarna** [comment]
> how to configure host (ip, dns) and port for receive conecctions?

Client side: 
### Go to Console Application 4.cpp and edit this

int PORT_NO = 7465;
        String^ SERVER_IP = "Your IP";

**Comment by SpaceR3** [comment]
Damn, somebody actually knows more than copy pasting.

**Comment by SpaceR3** [comment]
> > how to configure host (ip, dns) and port for receive conecctions?
> 
> Client side:
> 
> ### Go to Console Application 4.cpp and edit this
> int PORT_NO = 7465;
> String^ SERVER_IP = "Your IP";
> 
> Server Side:
> 
> ### Go to Forum 1 .cs and edit only port because it willl take your local host ip
> void Listen()
> {
> TcpListener server = null;
> Int32 port = 7465;
> IPAddress localAddr = IPAddress.Any;
> server = new TcpListener(localAddr, port);
> server.Start();

good job
