### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by graysuit** [SpaceR3/TewQ#5]
Yesterday I was seeing your RAT code,
Since I was pretty impressed and I also wanted to make keylogger more powerful,

And I was thinking what would have happen when developers like you die,
There are already tons of idiots like me,
So open source will shutdown,
Open source is gift from god,
We should not think bad but should prepare for worst,
Sorry again.

**Comment by SpaceR3** [comment]
sorry for what`?

**Comment by graysuit** [comment]
![Capture](https://user-images.githubusercontent.com/54432616/89040195-cb54b680-d35c-11ea-8de2-d7a2073bdb6e.PNG)

**Comment by graysuit** [comment]
You have taken my hidden jokes to your heart,
But I apologize for it.

**Comment by omgnobody121** [comment]
Yo bro, i am sorry. I did not block you, all my friends got removed. You can add me back, this is my second Github since the other one i lost  access to. Tewni#4641

**Comment by graysuit** [comment]
@tewni-svg 
No problem bro,
I was thinking that he has taken my words to his heart,
But I am sorry I realised after some days that I said some bitter words.
I have 2 year experience at making keylogger,I will set your keylogger component.ok 
And I am pretty happy that you have aware me that your account was hacked,So I have now unfriended that person so that he may not harm me Thanks.
